services:
  db:
    image: postgres:16-alpine
    container_name: academic_demo_db
    environment:
      POSTGRES_DB: academic_demo
      POSTGRES_USER: academic_demo
      POSTGRES_PASSWORD: academic_demo
    ports:
      - "5433:5432"
    volumes:
      - academic_demo_pgdata:/var/lib/postgresql/data

volumes:
  academic_demo_pgdata:
